config/routes.rb
Rails.application.routes.draw do
  #legacy
  get '/dev',   to: redirect("/course")
  get '/web',   to: redirect("/course")
  get '/method',  to: redirect("/course")
  get '/teachers',to: redirect("/course#teachers")
  get '/sponsoring',to: redirect("/sponsor_diversity")
  get '/marketingjob',   to: redirect("/")

  namespace :admin do
    resources :users
    resources :courses
    resources :resumes
    resources :applies

    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: "registrations" }

  resource  :resume , except: [:destroy , :new , :edit] do
    get :progress, on: :member
  end
  get :application , to: "applies#show"
  post :application , to: "applies#create"
  post :cancel_application , to: "applies#cancel"


  root to: 'high_voltage/pages#show' , id: 'index'

  get "/blog" , to: "blog#index" , as: :blog_index
  get "/blog/*title" , to: "blog#page" , as: :blog_page
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user

  default_scope {order('created_at DESC') }

  def percent
    attribs = percent_attributes
    non_nil = attribs.sum{ |name| self.attributes[name].blank? ? 0 : 1}
    (non_nil * 100) / attribs.length
  end

  def percent_attributes
    Resume.column_names - ["id" , "user_id" , "created_at", "updated_at"]
  end
end

app/controllers/admin/resumes_controller.rb
module Admin
  class ResumesController < AdminController
    def index
      @q = Resume.search params[:q]
      @resume_scope = @q.result(:distinct => true)
      @resumes = @resume_scope.page( params[:page] )
    end

    def show
      @resume = Resume.find(params[:id])
    end
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_resume, only: [:show, :update , :progress ]

  def show
  end

  def progress
    render layout: false
  end

  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = current_user.resume
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:user_id , :finance ,
                                     :school, :uni, :internship, :work, :tech_skills,
                                     :soft_skills, :projects, :other, :interests, :motivation)
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper


  # define a bunch of defaults for the best_in_place call
  def resume_in_place field , attributes = {}
    txt = I18n.t("resumes.#{field}")
    button = @resume.send(field).blank? ? "Ok" : "Edit"
    br = proc {|txtt| raw(txtt.to_s.gsub("\n" , "<br>")) }
    defaults = { :url => resume_path , place_holder: txt , display_with: br}
    unless [:street , :city , :country].include? field
      defaults.merge! ok_button: button,  ok_button_class: "btn btn-success" ,
                      cancel_button: "Cancel" , cancel_button_class:  "btn btn-warning",
                      inner_class:  "form-control" , as: :textarea ,
                      sanitize: false , html_attrs: {rows: 10}
    end
    attributes.reverse_merge! defaults
    best_in_place(@resume , field , attributes)
  end

end

app/views/resumes/progress.html.haml
- if @resume.percent == 100
  - if current_user.application
    .callout.alert.alert-default.margin-top-50.margin-bottom-50
    .row
      .col-md-8.col-sm-8
        %h4
          Your Application has been submitted, see it
          = link_to "here" , application_path
  - else
    .callout.alert.alert-default.margin-top-50.margin-bottom-50
      .row
        .col-md-8.col-sm-8
          %h4
            You can now apply for specific dates.
        .col-md-4.col-sm-4.text-right
          = link_to "APPLY" , application_path , class: "btn btn-primary"
- else
  %h4.margin-top-50
    Tell us about yourself and why you want to become a developer.
  %p

    Click on the fields to edit.
    While editing, clicking outside the box cancels.

  .progress
    .progress-bar{ "aria-valuemax" => "100",
                   "aria-valuemin" => "0",
                   "aria-valuenow" => "#{@resume.percent}",
                   :role => "progressbar",
                   :style => "width: #{@resume.percent}%; min-width: 2em;"}
      =@resume.percent
      \%

app/views/resumes/show.html.haml
.row
  .col-md-2
  .col-md-8
    #progress
    %br
.row
  .col-md-1
  .col-md-1
    %p
      %b School:
  .col-md-8
    = resume_in_place  :school
.row
  .col-md-1
  .col-md-1
    %p
      %b Uni:
  .col-md-8
    = resume_in_place  :uni
.row
  .col-md-1
  .col-md-1
    %p
      %b Internship:
  .col-md-8
    = resume_in_place  :internship
.row
  .col-md-1
  .col-md-1
    %p
      %b Work:
  .col-md-8
    = resume_in_place  :work
.row
  .col-md-1
  .col-md-1
    %p
      %b Projects:
  .col-md-8
    = resume_in_place  :projects
.row
  .col-md-1
  .col-md-1
    %p
      %b Tech skills:
  .col-md-8
    = resume_in_place  :tech_skills
.row
  .col-md-1
  .col-md-1
    %p
      %b Soft skills:
  .col-md-8
    = resume_in_place  :soft_skills
.row
  .col-md-1
  .col-md-1
    %p
      %b Intrests:
  .col-md-8
    = resume_in_place  :interests
.row
  .col-md-1
  .col-md-1
    %p
      %b Motivation:
  .col-md-8
    = resume_in_place  :motivation
.row
  .col-md-1
  .col-md-1
    %p
      %b Finance plan:
  .col-md-8
    = resume_in_place  :finance
.row.margin-bottom-30
  .col-md-1
  .col-md-1
    %p
      %b Other:
  .col-md-8
    = resume_in_place  :other